from mongoengine import *


class BankAgency(Document):

    Bank = StringField(max_length=3) 
    Branch = StringField(max_length=4) 
    Type = StringField(max_length=50) 
    BankName = StringField(max_length=50)
    BankNickName = StringField(max_length=50) 
    BranchName = StringField(max_length=50) 
    AttendedOrganization = StringField(max_length=50)
    ZIP = StringField(max_length=50) 
    x = StringField(max_length=50) 
    y = StringField(max_length=50) 
    BankCategory = StringField(max_length=50)
    Annexation = StringField(max_length=50)
    Differentiation = StringField(max_length=50)
    Recency = StringField(max_length=50)
    Activity = StringField(max_length=50)
    Unicity = StringField(max_length=50) 
    StartDate = StringField(max_length=50)
    LastStand = StringField(max_length=50) 
    PopulationalRank = StringField(max_length=50)
    OutskirtsReference = StringField(max_length=50)
    TownCharacteristics = StringField(max_length=50)
    Region = StringField(max_length=50)
    AddressStreet = StringField(max_length=50)
    AddressNumber = StringField(max_length=50)
    AddressComplement = StringField(max_length=50)
    Neighborhood = StringField(max_length=50)
    City = StringField(max_length=50)
    State = StringField(max_length=50)
    SRFGraphy = StringField(max_length=50)
    BranchNickName1 = StringField(max_length=50)
    BranchNickName2 = StringField(max_length=50)
    BranchNickName3 = StringField(max_length=50)
    BranchNickName4 = StringField(max_length=50)
    BranchNickName5 = StringField(max_length=50)
    BranchNickName6 = StringField(max_length=50)
    BranchNickName7 = StringField(max_length=50)
    BranchNickName8 = StringField(max_length=50)
    BranchNickName9 = StringField(max_length=50)
    BranchNickName10 = StringField(max_length=50)